version: '3.8'

services:
 
  db:
    image: postgres:15-alpine
    container_name: netflix_db
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: netflix_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mongo:
    image: mongo:6
    container_name: netflix_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./Backend
    container_name: netflix_backend
    ports:
      - "4000:4000"
    depends_on:
      - db
      - mongo
    environment:
      DATABASE_URL: "postgresql://user123:password123@db:5432/netflix_db?schema=public"
      MONGO_URL: "mongodb://mongo:27017/animeflix_db"
      JWT_SECRET: "ton_super_secret"
      JWT_EXPIRES_IN: "1h"
      JWT_REFRESH_SECRET: "ton_refresh_secret"
      JWT_REFRESH_EXPIRES_IN: "7d"
    volumes:
      - ./Backend:/app
      - /app/node_modules

  frontend:
    build: ./Frontend
    container_name: netflix_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
  mongo_data: